# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Minitest::Assertion; end
module ::Minitest::Assertions; end
module ::Minitest::Test; end
module ::TTY::Command; end
module ActionMailer::Base::Mail::Message; end
module ActiveRecord::Base::GlobalID::Identification; end
module ActiveSupport::ParameterFilter; end
